### ISSUE TITLE
Add `--version` option to fast_carpenter command

### ISSUE THREAD

**Issue by benkrikler** [FAST-HEP/fast-carpenter#74]
As suggested by @63990

**Comment by gunjanraval** [comment]
Can you elaborate on this issue?

**Comment by benkrikler** [comment]
Hi @gunjanraval, the idea is to add an option in `fast_carpenter.__main__.py` to print the version info contained in `fast_carpenter.version.py` and exit the program.

**Comment by maikefischer** [comment]
Can I work on this?

**Comment by benkrikler** [comment]
Please feel free!

**Comment by maikefischer** [comment]
Done! :-)
