### ISSUE TITLE
Don't allow `ncores==0`

### ISSUE THREAD

**Issue by benkrikler** [FAST-HEP/fast-carpenter#75]
We've noticed that `ncores == 0` (the default) is much slower than `ncores == 1`.  They should mean the same thing, so we should just protect `ncores==0` from being passed through to AlphaTwirl.  This should be easy enough to change in `fast_carpenter.__main__.py`.

**Comment by annakau** [comment]
Can I try tro fix this? Is it enough to just change the default or should it always change possible argument from 0 to 1? (I hope I understand this right)

**Comment by benkrikler** [comment]
Hi @annakau!  At the very least we should set the default to be `1` but I think we could also validate that a user hasn't provided less than `1`, and set to 1 if so.

**Comment by benkrikler** [comment]
Solved in #76
