### ISSUE TITLE
Give "fast-carpenter" to fast-flow to use as the back-end

### ISSUE THREAD

**Issue by benkrikler** [FAST-HEP/fast-carpenter#84]
We use [fast-flow](https://github.com/FAST-HEP/fast-flow/) to handle the loading of the processing configuration.  It has an option to provide a "default" backend which provides modules to load in.  However, fast-carpenter doesn't provide such an option at this point.

To set this up, it's enough to add `backend="fast_carpenter"` as an option on this line:
https://github.com/FAST-HEP/fast-carpenter/blob/master/fast_carpenter/__main__.py#L71
which calls this function from fast-flow: https://github.com/FAST-HEP/fast-flow/blob/master/fast_flow/v1/__init__.py#L10

This relates to issue #36 as well.

**Comment by lorenafreitas** [comment]
I'd like to work on this one!  💪

**Comment by benkrikler** [comment]
Wow!  Well that really was FAST :sunglasses: !  It's all yours
